{% set name = "pyrtools" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrtools-{{ version }}.tar.gz
  sha256: 0abfb5a7ccac9b40c8f9cdbc15edb4bd0090c7eed01dac9e9d668ed37bc8f99f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python
    - numpy >=1.1
    - scipy >=0.18
    - matplotlib-base >=1.5
    - tqdm >=4.29
    - requests >=2.21

test:
  imports:
    - pyrtools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python tools for multi-scale image processing, including Laplacian pyramids, Wavelets, and Steerable Pyramids.
  home: https://github.com/LabForComputationalVision/pyrtools/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - billbrod
